#!/usr/bin/env bash

git diff --numstat $* | gawk 'BEGIN { files = 0; } { files +=1; add += $1; subs += $2; loc += $1 - $2 } END { printf "%s files changed\n", files; printf "%s\t%s\t%s\n", add, subs, loc }' -;
